### ISSUE TITLE
License violations were found

### ISSUE THREAD

**Issue by DaveJarvis** [kordamp/desktoppanefx#16]
# Replicate

Attempted to update the demo application to use JavaFX 11 and Gradle 6.6.1.

1. Download [desktop-pane-fx.zip](https://github.com/kordamp/desktoppanefx/files/5427412/desktop-pane-fx.zip).
1. Unzip the archive.
1. Change to the project directory.
1. Run: gradle clean build

# Expected

Application builds.

# Actual

``` plain
Missing header in: subprojects/desktoppanefx-core/desktoppanefx-core.gradle
> Task :desktoppanefx-core:licenseGradle FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktoppanefx-core:licenseGradle'.
> License violations were found: /home/username/dev/java/desktoppanefx/subprojects/desktoppanefx-core/desktoppanefx-core.gradle}
```

# Environment

Liberica JDK 14 (full), Linux (XFCE/X11), IntelliJ 2020 (recent version), Gradle 6.6.1

**Comment by aalmiray** [comment]
The file `desktoppanefx-core.gradle` has the correct license header in the master branch -> https://github.com/kordamp/desktoppanefx/blob/master/subprojects/desktoppanefx-core/desktoppanefx-core.gradle

Did you remove or update the header as part of the upgrade?
This can be fixed by running `gradle licenseFormat`.

**Comment by DaveJarvis** [comment]
I wasn't able to get this to build with JavaFX 11, JDK 14, and Gradle 6.6.1. Are there build instructions for such a combination?

**Comment by aalmiray** [comment]
I believe the major stumbling block is using the `openjfx` gradle plugin to resolve the JavaFX dependencies. You can have a look at a project that has the plugin configured at https://github.com/HanSolo/tilesfx/blob/master/build.gradle

Take note that the `openjfx` plugin will generate a POM with resolved classifiers which is *bad* for consumers. The TilesFX build has a block that removes said classifiers.

Unfortunately Gradle offers no support for creating multi release JARs without pain which is why the DesktopPaneFX build remains Java 8 compatible for the time being.
